language: android

env:
  - REVIEWDOG_VERSION=0.9.11

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x deploy_bintray.sh
  - chmod +x add_review.sh

script:
  - ./gradlew lintKotlin
  - ./gradlew test --info

after_failure:
  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ./reviewdog
  - chmod +x ./reviewdog
  - ./add_review.sh

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_bintray.sh
