[versions]
coroutines = "1.10.2"
jackson = "2.21.0"
junit = "4.13.2"
moshi = "1.15.2"
okhttp = "5.0.0-alpha.16"
forge = "1.0.0-alpha3"
result = "5.6.0"
serialization = "1.10.0"
kotlinx-io = "0.8.2"
kover = "0.9.4"
kotlin = "2.3.0"
ksp = "2.3.4"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-io", version.ref = "serialization" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
okhttp-coroutines = { group = "com.squareup.okhttp3", name = "okhttp-coroutines", version.ref = "okhttp" }
forge = { group = "com.github.kittinunf.forge", name = "forge", version.ref = "forge" }
result = { group = "com.github.kittinunf.result", name = "result", version.ref = "result"}
result-jvm = { group = "com.github.kittinunf.result", name = "result-jvm", version.ref = "result"}

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref="ksp" }
